project:
  language: java


services:
  mysql:
    image: 'mysql:5.7'
    type:
      - testing
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
  postgres:
    image: 'postgres:9.6.8'
    type:
      - testing
    environment:
      POSTGRES_PASSWORD: 'postgres'
  rest-server:
    image: 'spdc1k8sregistry11.privalia.pin/privalia-rest-server:0.1.0'
    type:
      - testing
  demo-site:
    image: 'spdc1k8sregistry11.privalia.pin/privalia-front-image:0.1.0'
    type:
      - testing
  selenium-grid:
    image: 'spdc1k8sregistry11.privalia.pin/privalia-selenium-hub:3.7.1'
    type:
      - testing
  selenium-chrome:
    image: 'spdc1k8sregistry11.privalia.pin/privalia-selenium-chrome:62'
    type:
      - testing

pipeline:
  artifact_type: "library"
  stages:
    UnitTest:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install -DVERSION=1.0 -DSLEEPTEST=3 -DAGENT_LIST=1,2 -DVARNAME=foo -DPOSTGRES_HOST=postgres -DMYSQL_HOST=mysql -DREST_SERVER_HOST=rest-server -DDEMO_SITE_HOST=demo-site -DSELENIUM_GRID=selenium-grid:4444"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    Build:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install -Dmaven.test.skip=true"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    CleanRequirements:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean"
      volumes:
        m2-cache: '/home/jenkins/.m2'
