project:
  language: java


services:
  mysql:
    image: 'mysql:5.7'
    type:
      - testing
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
  postgres:
    image: 'postgres:latest'
    type:
      - testing
    environment:
      POSTGRES_PASSWORD: 'postgres'

pipeline:
  artifact_type: "library"
  stages:
    UnitTest:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install -DVERSION=1.0 -DSLEEPTEST=3 -DAGENT_LIST=1,2 -DVARNAME=foo -DPOSTGRES_HOST=postgres -DMYSQL_HOST=mysql"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    Build:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install -Dmaven.test.skip=true"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    CleanRequirements:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean"
      volumes:
        m2-cache: '/home/jenkins/.m2'
