project:
  language: java


services:
  mysql:
    image: 'mysql:5.6'
    type:
      - testing
    environment:
      MYSQL_ROOT_PASSWORD: "mysql"
  postgres:
    image: 'postgres:9.6.8'
    type:
      - testing
    environment:
      POSTGRES_PASSWORD: 'postgres'
  rest-server:
    image: 'harbor.privalia-test.com/qa/privalia-rest-server:0.1.0'
    type:
      - testing
  demo-site:
    image: 'harbor.privalia-test.com/qa/privalia-front-image:0.1.0'
    type:
      - testing
  selenium-grid:
    image: 'harbor.privalia-test.com/qa/privalia-selenium-hub:3.9.1'
    type:
      - testing
  selenium-chrome:
    image: 'harbor.privalia-test.com/qa/privalia-selenium-chrome:64'
    type:
      - testing
    environment:
      ID: 'myBrowser'
      SELENIUM_GRID: 'selenium-grid:4444'
  kafka:
    image: 'landoop/fast-data-dev:1.0.1'
    environment:
      - ADV_HOST=localhost

pipeline:
  artifact_type: "library"
  stages:
    UnitTest:
      image: "harbor.privalia-test.com/qa/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install -DVERSION=1.0 -DSLEEPTEST=3 -DAGENT_LIST=1,2 -DVARNAME=foo -DPOSTGRES_HOST=postgres -DMYSQL_HOST=mysql -DREST_SERVER_HOST=rest-server -DDEMO_SITE_HOST=demo-site -DSELENIUM_GRID=selenium-grid:4444 -DZOOKEEPER_HOST=kafka -DSCHEMA_REGISTRY_HOST=kafka"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    Build:
      image: "harbor.privalia-test.com/qa/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install -Dmaven.test.skip=true"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    CleanRequirements:
      image: "harbor.privalia-test.com/qa/privalia-qa-worker:0.1.0"
      cmd: "mvn clean"
      volumes:
        m2-cache: '/home/jenkins/.m2'
