project:
  language: java
  environments:
      APP_ENV: '%env%'
      APPDYNKEY: '%appdynkey%'
      TAG_APP: '%tagApp%'
      TAG_PROJECT: '%tagProject%'
      TAG_CONF: '%tagConf%'

services:
  mysql:
    image: spdc1k8sregistry11.privalia.pin/mysql
    type:
      - testing
    environment:
      MYSQL_USER: root
      MYSQL_ROOT_PASSWORD: mysql
  postgres:
      image: postgres
      type:
        - testing
      environment:
        POSTGRES_PASSWORD: postgres


pipeline:
  artifact_type: "library"
  stages:
    Build:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean install -DVERSION=1.0 -DSLEEPTEST=3 -DAGENT_LIST=1,2 -DVARNAME=foo"
      volumes:
        m2-cache: '/home/jenkins/.m2'
    CleanRequirements:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      cmd: "mvn clean"
      volumes:
        m2-cache: '/home/jenkins/.m2'
