project:
  language: java
pipeline:
  artifact_type: "library"
  stages:
    Build:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      uid: '0'
      cmd: "mvn clean install -Dmaven.test.skip=true"
      volumes:
        m2-cache: '/root/.m2'
    CleanRequirements:
      image: "spdc1k8sregistry11.privalia.pin/privalia-qa-worker:0.1.0"
      uid: '0'
      cmd: "mvn clean"
